language: java
jdk:
  - oraclejdk8

env:
  global:
    - CODACY_PROJECT_TOKEN=e9c07f97fad84186826f873f384a6112

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 2>./openssl-connect.stderr | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' ]]; then git remote add upstream https://github.com/hmcts/$(echo ${TRAVIS_REPO_SLUG} | cut -d "/" -f2).git; git remote -v; fi
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' ]]; then git fetch upstream master; fi
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' ]]; then git log -1 --pretty=format:%H upstream/master; fi
  - if [[ ${TRAVIS_BRANCH} == 'coverity_scan' ]]; then git rebase upstream/master; fi

script:
  - if [[ ${COVERITY_SCAN_BRANCH} == 1 ]];
    then
        echo "Don't build on coverty_scan branch.";
        exit 0;
    fi
  - "./gradlew build"
  - "./gradlew codeCoverageReport || echo 'code coverage upload failed'"

after_success:
  - "bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'"

addons:
  coverity_scan:
    project:
      name: "dwaynebailey/ccd-definition-store-api"
      description: "CCD Definition Store API"
    notification_email: Dwayne.Bailey@HMCTS.net
    build_command: ./gradlew build
    branch_pattern: coverity_scan
